---
- name: create directory for application
  file:
    path: /opt/github-hook-relay
    state: directory

- name: install github-hook-relay
  unarchive:
    src: "https://github.com/roundpartner/github-hook-relay/releases/download/{{ github_hook_relay_version }}/github-hook-relay.zip"
    dest: /opt/github-hook-relay
    remote_src: yes

- name: install supervisor
  package:
    name: supervisor
    state: present

- name: install template
  template:
    src: github-hook-relay.ini
    dest: /etc/supervisord.d/github-hook-relay.ini
  notify: restart supervisor

- name: start supervisor
  service:
    name: supervisord
    state: "{{ relay_service_state }}"
    enabled: yes
...